### ISSUE TITLE
Can't build on Linux (64bit, Ubuntu 14.04)

### ISSUE THREAD

**Issue by Uplink03** [xsmart/opencvr#14]
When I try to compile on Ubuntu 14.04, 64bit, I end up with this:

    make[2]: *** No rule to make target `../vms/vscrecorderadd.ui', needed by `GeneratedFiles/ui_vscrecorderadd.h'. Stop.
    make[2]: Leaving directory `/home/me/Code/opencvr/veapp/prj_linux'
    make[1]: *** [vepro_build] Error 2
    make[1]: Leaving directory `/home/me/Code/opencvr/veapp'

**Comment by xsmart** [comment]
current Opencvr don't open the linux build makefile, you can use the pre-build version

**Comment by Uplink03** [comment]
So Zoneminder 1.28 with libvlc it is then.
