### ISSUE TITLE
LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by clmarshall** [xsmart/opencvr#23]
Within Instructions, the settings for LD_LIBRARY_PATH is incomplete.

If both Qt is installed in User Directory (as is default), and the Open-CVR archive is extracted in the User Directory the values for LD_LIBRARY_PATH should be within ./env.sh should be:

export LD_LIBRARY_PATH=/home/**[USER]**/OpenCVR-Ubuntu14.04-CentOS7-64bit-r1.2.3/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/home/**[USER]**/Qt5.4.0/5.4/gcc_64/lib:$LD_LIBRARY_PATH 

**Note: Replace [USER] with the username, without brackets**

**Comment by xsmart** [comment]
please use 2.0 version
