### ISSUE TITLE
Drive does not list HDD

### ISSUE THREAD

**Issue by clmarshall** [xsmart/opencvr#25]
In the Drive section the local HDD is not displayed.

![de](https://cloud.githubusercontent.com/assets/3595063/8211449/e440a1f4-14e4-11e5-9638-4b711eb5f23b.png)

**Below is the console output that begins when I click on 'Edit' under 'Disks':**
2015/06/17 06:25:22 AM [V]: EditDisk
2015/06/17 06:25:22 AM [V]: VSCHddEdit strHdd / 
2015/06/17 06:25:22 AM [V]: VSCHddEdit Total 13612 M Left 7363 M 
2015/06/17 06:25:22 AM [V]: VSCHddEdit Type 1 
2015/06/17 06:25:22 AM [V]: VSCHddEdit strHdd /run/user/1000/gvfs 
2015/06/17 06:25:22 AM [V]: VSCHddEdit Total 0 M Left 0 M 
2015/06/17 06:25:22 AM [V]: VSCHddEdit Type 1 
2015/06/17 06:25:22 AM [V]: VSCHddEdit strHdd /mnt/opencvr 
2015/06/17 06:25:22 AM [V]: VSCHddEdit Total 13612 M Left 7363 M 
2015/06/17 06:25:22 AM [V]: VSCHddEdit Type 1

**Comment by xsmart** [comment]
in the vschdddevice.cpp
	if (totalSize/1024 < 16 || leftSize/1024 < 4)
	{
	    continue;
	}

if your disk < 16G, then skip
