### ISSUE TITLE
Double Link List Error

### ISSUE THREAD

**Issue by clmarshall** [xsmart/opencvr#28]
2015/07/18 11:58:08 AM [V]: MFramework runing
*** Error in `./bin/OpenCVR': corrupted double-linked list: 0x00007fe335d3bb20 ***
./start.sh: line 4:  9561 Aborted                 (core dumped) ./bin/OpenCVR

-- Occurs within 2 - 12 hours of running 5 cameras in record on Ubuntu x64

**Comment by xsmart** [comment]
please try the 2.0.3 version
