### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by edgiru** [xsmart/opencvr#30]
Is it possible to:
that are easy to install and tightens itself addiction?
make it self-service access through the web interface (zoneminder)?

**Comment by xsmart** [comment]
we will have full function client on android and ios instead of the web interface, is it enough?

**Comment by edgiru** [comment]
This device with a small screen, you want to view in high quality, according to this preferred a regular computer. Thank you for your work. But I would like a full-fledged Linux-based server with access via the web interface.

**Comment by xsmart** [comment]
current the Chrome and IE both disable the plugin, so for the high quality can not be view in the web interface. so the opencvr also support connect another opencvr as a client.

**Comment by edgiru** [comment]
opencv required for qt but it is only set visual interface (x system) can not be set through the command line. And without qt as I understood your system is not working.

**Comment by xsmart** [comment]
the OpenCVR can start without x system. but it also depend the Qt system.

**Comment by xsmart** [comment]
please use 2.0 version
