### ISSUE TITLE
OpenCVR: No such file or directory

### ISSUE THREAD

**Issue by alegorosito** [xsmart/opencvr#33]
Hi guys.

I'm triying to follow your steps to configure the opencvr:
http://download.qt-project.org/official_releases/qt/5.4/5.4.0/qt-opensource-linux-x64-5.4.0.run 
   ---> add below 2 line into /etc/profile
export  PATH=/home/xxx/Qt5.4.0/5.4/gcc_64/bin:/home/xxx/Qt5.4.0/Tools/QtCreator/bin/:$PATH
export  VE_QTDIR=/home/xxx/Qt5.4.0/5.4/gcc_64/
2.edit the env.sh LD_LIBRARY_PATH for the current dir
   source ./env.sh
   ./start.sh

But, when I execute ./start I had this error: 
./bin/OpenCVR: No such file or directory

Maybe I'm skipping some steps. Can you tell me something about it?

OS: Ubuntu 14.04 64bits

**Comment by xsmart** [comment]
have you down load linux version opencvr,maybe  the opencvr file not exist.

**Comment by alegorosito** [comment]
I think I am using the Linux version, but you could tell me what is the link to that version? Thank you.

**Comment by angelscopilo** [comment]
![opencvv_ubuntu](https://cloud.githubusercontent.com/assets/14018627/11011698/ed487a30-84b8-11e5-8f36-4a80b6f597af.png)
![processrunning](https://cloud.githubusercontent.com/assets/14018627/11011700/ef7bcda2-84b8-11e5-90b7-d2735ffd373c.png)
![screenshot from 2015-11-06 18 30 20](https://cloud.githubusercontent.com/assets/14018627/11011701/f1ccc7dc-84b8-11e5-8f65-ee619af20072.png)
This is how I got to work. I'm running the same ubuntu 14 
PS the problem is that I can't get to run again :-(

**Comment by angelscopilo** [comment]
![screenshot from 2015-11-06 19 19 50](https://cloud.githubusercontent.com/assets/14018627/11011954/9379303c-84bb-11e5-9a47-ac18e4025056.png)

Ok I got it ot work again and again.... Success Nice program but the instruction are bit vague here is how I Got to work in the terminal 
sudo su-p 
this will give root access and better permission. 
cd home or your directory or folder where is the OpenCVR folder is
ls (should list all the folders and files)
 <the files you are looking for is the Folder OpenCVR> 
mv OpenCVR //
(this will move the folder to the root dir)
root@Ubuntu-dev://# ls
     OpenCVR 
root@Ubuntu-dev://# 
cd OpenCVR
gedit env.sh 
![screenshot from 2015-11-06 19 31 53](https://cloud.githubusercontent.com/assets/14018627/11012087/17fa1b9a-84bd-11e5-91d9-7e12b8781863.png)
above show how I edit the env.sh 
and I type the commands:
source ./env.sh
sh start.sh
I now this work for me  hope this work for you. 
![screenshot from 2015-11-06 19 34 36](https://cloud.githubusercontent.com/assets/14018627/11012116/98ef882a-84bd-11e5-87b9-eedd91b0c1a0.png)

**Comment by angelscopilo** [comment]
PS: Also the add it benefit to this running on root level is that the program can write to the hard disk you assign since running on level user crash the program.

**Comment by angelscopilo** [comment]
![screenshot from 2015-11-06 20 29 51](https://cloud.githubusercontent.com/assets/14018627/11012684/9454f59a-84c5-11e5-807b-99cff16fafb0.png)
Here is a screen shot of another problem. HELP 
It froze while playback. no response to mouse or any input It give this 
terminate called after throwing an instance of 'Poco::FileAccessDeniedException'
  what():  Access to file denied

**Comment by alegorosito** [comment]
Thank you very much, angelscopilo.

My big problem is that I have the OpenCVR folder (Is the main folder?) ... So I do not have the lib folder should be inside. May I ask where you downloaded OpenCVR?

I download it from this repo https://github.com/xsmart/opencvr

I think I'm doing something wrong or I am missing files. Look at my files ...

![captura de pantalla de 2015-11-09 11 52 19](https://cloud.githubusercontent.com/assets/2251847/11036606/5c496c0c-86d8-11e5-9013-519e0b74e3f0.png)

**Comment by angelscopilo** [comment]
http://sourceforge.net/projects/vscloud/files/OpenCVR-Ubuntu14.04-CentOS7-64bit-r1.2.3.tar.gz/download 

This the direct link were I download it they are only the ubuntu files. 
however if you can see the linux folder in your directory they are there too

**Comment by alegorosito** [comment]
That worked perfectly angelscopilo. Thank you!
Now I'm trying to compile from source. According to the steps of the wiki:
     $ cd opencvr
     $ source ./rules.mk
     $ make
Can you give me some advice about this?

**Comment by exceeded** [comment]
Hi @alegorosito, unfortunately the source doesn't compile for Linux at the moment... https://github.com/xsmart/opencvr/issues/26#issuecomment-155107014

The latest version for build is 1.2.3. I've sent an email to veyesys to see if they can reupload/upload the correct files and a build!

**Comment by alegorosito** [comment]
That's what I wanted to hear ... I've been trying to compile a while. Thanks for clearing that up. I hope they can fix it soon.

**Comment by exceeded** [comment]
Yeah, they've basically not added in one of the components that was added.

I can probably fix it by omitting the references but that's not a good idea I don't think...

**Comment by alegorosito** [comment]
@exceeded Perhaps I can compile on Windows and then create binaries for Linux? I would like to add specific functionality to the project.

**Comment by exceeded** [comment]
Yes, same... It's worth a shot? Let me know if I can help...

@xsmart any comments at all? We need your help!

**Comment by xsmart** [comment]
next version will split the server and client, and OpenCVR will include Qt itself.

**Comment by angelscopilo** [comment]
Do you have a timeframe on new version. also I would not mind paying for some ability to customize the logo and or entry screen, of course always giving due credit to the owners

**Comment by xsmart** [comment]
Maybe 2016 Jan we can have the first version, we can nail down the detail time frame middle of 2015 Dec.

**Comment by ictele** [comment]
Hi, to start building, you have to run ./start.sh. I searched the whole folder and could not find this file in linux and could not find it from source list (Web Page). Do I have prepare for it by myself?

**Comment by ictele** [comment]
I met similar troubles. Who could comment them?

Built from repository 2152 and Qt has been installed.

**Linux (Debian 8 32bit)**
cd ./prj_linux/ ; qmake .;
Project MESSAGE: You are running qmake on a generated .pro file. This may not work!
WARNING: Failure to find: ../src/config/vidstor/disksetting/vschddedit.cpp
WARNING: Failure to find: ../src/config/vidstor/disksetting/vschddoneedit.cpp
WARNING: Failure to find: ../src/config/vidstor/camsetting/vsccaminfo.cpp
WARNING: Failure to find: ../src/config/vidstor/camsetting/vsccamrec.cpp
WARNING: Failure to find: ../src/config/vidstor/disksetting/vschddedit.h
WARNING: Failure to find: ../src/config/vidstor/disksetting/vschddoneedit.h
WARNING: Failure to find: ../src/config/vidstor/camsetting/vsccaminfo.h
WARNING: Failure to find: ../src/config/vidstor/camsetting/vsccamrec.h
WARNING: Failure to find: ../src/config/vidstor/disksetting/vschddedit.ui
WARNING: Failure to find: ../src/config/vidstor/disksetting/vschddoneedit.ui
WARNING: Failure to find: ../src/config/vidstor/camsetting/vsccaminfo.ui
WARNING: Failure to find: ../src/config/vidstor/camsetting/vsccamrec.ui
make -C ./prj_linux;
make[2]: Entering directory '/home/sk0000/share/opencvr_2152/client/prj_linux'
make[2]: *** No rule to make target '../src/config/vidstor/disksetting/vschddedit.ui', needed by 'GeneratedFiles/ui_vschddedit.h'.  stoped.
make[2]: Leaving directory '/home/sk0000/share/opencvr_2152/client/prj_linux'
Makefile:7: recipe for target 'vepro_build' failed
make[1]: *** [vepro_build] Error 2
make[1]: Leaving directory '/home/sk0000/share/opencvr_2152/client'
Makefile:11: recipe for target 'all' failed
make: *** [all] Error 2


**Windows  (VS2013)**
Some files are missing. Such as "simplecrypt.hpp"


Thanks.

**Comment by xsmart** [comment]
you can use prebuild version, and the github souce code will be ready soon after we finished the playback function.

**Comment by ictele** [comment]
Prebuild version does not work with my sample neither RTSP address nor ONVIF.

**Comment by xsmart** [comment]
Skype : xsmart@veyesys.com , we can remote help you

**Comment by ictele** [comment]
Thanks. I think I have found the reason.
"The code files (downloaded from HTTPS with SVN Client) differ with ZIP package (got from HTTP). Missing files could be found in ZIP package. Now if I fix the problem of "QtWidgets/QMainWindow not found", all maybe goes well.

**Comment by xsmart** [comment]
please try the 2.0.3 version
