### ISSUE TITLE
OpenCVR-r2.0.1-Ubuntu-14.04-64bit-release

### ISSUE THREAD

**Issue by victorbrazil** [xsmart/opencvr#39]
When start ./startclient apperar

terminate called after throwing an instance of 'spdlog::spdlog_ex'
  what():  Failed opening file ve//vidstor/logs/opencvrclient.txt for writing

**Comment by xsmart** [comment]
this maybe last time start the client with the root, then you start as a not-root user, the log can not be accessed.
