### ISSUE TITLE
can't play rtsp

### ISSUE THREAD

**Issue by doanthaibao** [xsmart/opencvr#45]
I try some rtsp server link lik (rtsp://ip_address:554)
Those links can be played by VLC player.
How can I play or config camera with rtsp.
I tried 2 versions 1.3.3 and 2.0.1
Thanks
Bao

**Comment by xsmart** [comment]
is it ok? how can i help you ?

**Comment by doanthaibao** [comment]
It's ok but not stable. I try with rtsp server it usually can't play. I have to exit app and open to see video.
I use vlc it connect and get first frame faster than xsmart. Waiting for a long time to see first frame.
Anyway, It's awesome open source software.
