### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by ictele** [xsmart/opencvr#46]
Did someone successfully build the project from source? For unknown reason, I always fails by referring "build manual". What extra module/lib is necessary?
* I have configured Qt 5.4 to build repository 2170.
* In Windows, VS2013 Pro is used.
* In Debian 8, default modules have been installed.

Build from source Windows
Open the veuilib\prj_win32\veuilib.sln by vs2013 and build veuilib(if you do not have full source code, skip this)
Open the veapp\prj_win32\VSCloudNode.sln by vs2013 and build it.
Build from source Linux
$cd opencvr
$source ./rules.mk
$make

* VSCouldNote.sln could not be found in Repository 2170.

**Comment by xsmart** [comment]
i will add the missing files

**Comment by ictele** [comment]
Could you update the build readme?

**Comment by xsmart** [comment]
you can use 2.0.3 release version
