### ISSUE TITLE
Linux build from source missing file

### ISSUE THREAD

**Issue by Dehumanizer77** [xsmart/opencvr#47]
I have tried to build opencvr from source under Linux (Debian Wheezy) but the build ends up with this error:

In file included from ../src/main/vscmainwindows.h:12:0,
                 from ../src/main/main.cpp:8:
../src/main/vscdashboard.h:16:29: fatal error: ui_vscdashboard.h: No such file or directory
compilation terminated.

What's up with this missing file? Where can I get it?

**Comment by xsmart** [comment]
you can use the 2.0.3 release version
