### ISSUE TITLE
THIS PROJECT USE UNKNOWN ORIGIN CLOSED SOURCE LIBRARYS  VELIB AND VEUILIB!!!

### ISSUE THREAD

**Issue by laigor** [xsmart/opencvr#49]
ATTENTION!!! ATTENTION!!! This project is not completely open source. To compile and use this program, you need the unknown origin closed source librarys velib and veuilib. You can not compile the program for the arm and mips because velib and veuilib only available in binary form only for x86 and x64 architectures. Type of License for libraries velib and veuilib unknown! ВНИМАНИЕ!!! Этот проект является открытым только частично. Для компиляции и использования этой программы необходимы библиотеки с закрытым исходным кодом неизвестного происхождения velib и veuilib. Вы не можете скомпилировать эту программу под arm или mips поскольку velib и veuilib предоставляются только в бинарном виде и только для архитектуры x86 и x64. Тип лицензия для библиотек velib и veuilib неизвестна!

**Comment by xsmart** [comment]
yes, the velib and veuilib is in binary.

**Comment by xsmart** [comment]
All the source code will be open soon.
