### ISSUE TITLE
How to Install openCVR on CentOS?

### ISSUE THREAD

**Issue by eduardomunizbarreto** [xsmart/opencvr#55]

**Comment by xsmart** [comment]
https://xsmart.gitbooks.io/opencvrusermanual/content/installingmd.html

**Comment by eduardomunizbarreto** [comment]
Thanks for answering, but what sourceforge package, should I download?

**Comment by xsmart** [comment]
http://www.veyesys.com/ go to the download page

**Comment by xsmart** [comment]
The linux Ubunut 14.04, same with CentOS 7

**Comment by eduardomunizbarreto** [comment]
Oh man, sorry about that... Thanks again.
