### ISSUE TITLE
Can't build on linux 32bit

### ISSUE THREAD

**Issue by rathias** [xsmart/opencvr#9]
Hi,

I try to build opencvr on ubuntu 14.04 32bit and the compilation fails on veapp/prj_linux.
Make return error during linking of veapp because it can't find velib, veuilib and leveldb.
I try to find these library and it seems that only x64 and windows libraries are presents.

It is possible to get sources or build these libraries for linux 32bit?

Thanks!

**Comment by xsmart** [comment]
current the source code don't have the linux velib and veuilib, you can use prebuild version at https://sourceforge.net/projects/vscloud/, and i will put the two lib to the github for ubuntu 1404 x64 and centos7  x64 version

**Comment by xsmart** [comment]
i Have add the ubuntu 14.04 64bit. Building to the git master
